### ISSUE TITLE
train data와 test data의 distribution이 다름.

### ISSUE THREAD

**Issue by seopbo** [songys/Question_pair#1]
"kor_Pair_test.csv" 데이터 (a)와 "kor_pair_train.csv" 데이터 (b)의 distribution이 서로 달라, (b)로 학습한 모델로 (a)를 평가할 시 성능이 제대로 나오지 않습니다. (평가할 수 없음). 아래의 1의 구현에서 train data와 test data를 섞어서 다시 split하였고, 2의 구현에서도 1의 데이터를 활용함. 관련하여 데이터와 데이터 생성코드를 pr을 날리려고합니다. @songys 

1. https://github.com/aisolab/nlp_implementation/tree/master/BERT_pairwise_text_classification
2. https://github.com/SKT-AI/KoGPT2?fbclid=IwAR1kZiqqrBNUqQ_aFAx03JI0cA822J_IrxLarFuQwml5aLWYgJFuzGiuikc

**Comment by haven-jeon** [comment]
저도 해당 이슈때문에 @aisolab 님의 데이터를 사용하고 있습니다. 
감사합니다.

**Comment by songys** [comment]
@aisolab, @haven-jeon 코멘트 감사합니다! 우선 메인에 해당 이슈를 적어 두고 찬찬히 살펴 보겠습니다.  부족한 데이터 때문에 고생 많으십니다.  다행인건 조만간(?) 국어원에서 범용 데이터가 공개될 것 같습니다.

**Comment by songys** [comment]
아 그리고 @aisolab  pull request 주시면 저야 감사하죠!!

**Comment by songys** [comment]
다운로드하거나 위젯으로 데이터를 불러서 사용하시는 분들이 꾸준히 있어서 @aisolab 데이터로 업데이트하고 이슈를 닫습니다. 열심히 사용해 주시고 코멘트 주셔서 고맙습니다.
